Update dotnet-test.yml

diff --git a/.github/workflows/dotnet-test.yml b/.github/workflows/dotnet-test.yml
--- a/.github/workflows/dotnet-test.yml
+++ b/.github/workflows/dotnet-test.yml
@@ -73,21 +73,21 @@ jobs:
         echo "SDK version from dotnet tool is not as expected."
         exit 1
 
-    - name: Add GitHub Packages NuGet Source
-      env:
-        PACKAGES_READ_PAT: ${{ secrets.PACKAGES_READ_PAT }}
-      shell: bash # required when running on Windows
-      run: |
-        if [[ -z "$PACKAGES_READ_PAT" ]]; then
-          echo "::error::The required PACKAGES_READ_PAT secret is missing."
-          exit 1
-        fi
-        dotnet nuget add source \
-          https://nuget.pkg.github.com/CPC-Systems/index.json \
-          --name "CPC-Systems GitHub Packages" \
-          --username "USERNAME" \
-          --password "${PACKAGES_READ_PAT}" \
-          --store-password-in-clear-text
+    # - name: Add GitHub Packages NuGet Source
+    #   env:
+    #     PACKAGES_READ_PAT: ${{ secrets.PACKAGES_READ_PAT }}
+    #   shell: bash # required when running on Windows
+    #   run: |
+    #     if [[ -z "$PACKAGES_READ_PAT" ]]; then
+    #       echo "::error::The required PACKAGES_READ_PAT secret is missing."
+    #       exit 1
+    #     fi
+    #     dotnet nuget add source \
+    #       https://nuget.pkg.github.com/CPC-Systems/index.json \
+    #       --name "CPC-Systems GitHub Packages" \
+    #       --username "USERNAME" \
+    #       --password "${PACKAGES_READ_PAT}" \
+    #       --store-password-in-clear-text
     
     - name: Standard Restore # Not Including Windows Target(s) on Linux
       if: "!(matrix.os == 'ubuntu-22.04' && inputs.targets-windows)"
